// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bank_accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBankAccountDetails = `-- name: CreateBankAccountDetails :one
INSERT INTO bank_account_details (
    asset_id, bank_name, account_number, account_type
) VALUES (
    $1, $2, $3, $4
)
RETURNING asset_id, bank_name, account_number, account_type
`

type CreateBankAccountDetailsParams struct {
	AssetID       uuid.UUID `json:"asset_id"`
	BankName      string    `json:"bank_name"`
	AccountNumber string    `json:"account_number"`
	AccountType   string    `json:"account_type"`
}

func (q *Queries) CreateBankAccountDetails(ctx context.Context, arg CreateBankAccountDetailsParams) (BankAccountDetail, error) {
	row := q.db.QueryRow(ctx, createBankAccountDetails,
		arg.AssetID,
		arg.BankName,
		arg.AccountNumber,
		arg.AccountType,
	)
	var i BankAccountDetail
	err := row.Scan(
		&i.AssetID,
		&i.BankName,
		&i.AccountNumber,
		&i.AccountType,
	)
	return i, err
}

const getBankAccountDetailsByAssetID = `-- name: GetBankAccountDetailsByAssetID :one
SELECT asset_id, bank_name, account_number, account_type
FROM bank_account_details
WHERE asset_id = $1
`

func (q *Queries) GetBankAccountDetailsByAssetID(ctx context.Context, assetID uuid.UUID) (BankAccountDetail, error) {
	row := q.db.QueryRow(ctx, getBankAccountDetailsByAssetID, assetID)
	var i BankAccountDetail
	err := row.Scan(
		&i.AssetID,
		&i.BankName,
		&i.AccountNumber,
		&i.AccountType,
	)
	return i, err
}

const listBankAccountDetailsByAssetIDs = `-- name: ListBankAccountDetailsByAssetIDs :many
SELECT asset_id, bank_name, account_number, account_type
FROM bank_account_details
WHERE asset_id = ANY($1::uuid[])
`

// Batch fetch — used to populate details for a list of assets in one query
// (avoids N+1 lookups when listing bank accounts for a household).
func (q *Queries) ListBankAccountDetailsByAssetIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]BankAccountDetail, error) {
	rows, err := q.db.Query(ctx, listBankAccountDetailsByAssetIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankAccountDetail
	for rows.Next() {
		var i BankAccountDetail
		if err := rows.Scan(
			&i.AssetID,
			&i.BankName,
			&i.AccountNumber,
			&i.AccountType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBankAccountDetails = `-- name: UpdateBankAccountDetails :one
UPDATE bank_account_details
SET bank_name      = $2,
    account_number = $3,
    account_type   = $4
WHERE asset_id = $1
RETURNING asset_id, bank_name, account_number, account_type
`

type UpdateBankAccountDetailsParams struct {
	AssetID       uuid.UUID `json:"asset_id"`
	BankName      string    `json:"bank_name"`
	AccountNumber string    `json:"account_number"`
	AccountType   string    `json:"account_type"`
}

func (q *Queries) UpdateBankAccountDetails(ctx context.Context, arg UpdateBankAccountDetailsParams) (BankAccountDetail, error) {
	row := q.db.QueryRow(ctx, updateBankAccountDetails,
		arg.AssetID,
		arg.BankName,
		arg.AccountNumber,
		arg.AccountType,
	)
	var i BankAccountDetail
	err := row.Scan(
		&i.AssetID,
		&i.BankName,
		&i.AccountNumber,
		&i.AccountType,
	)
	return i, err
}
