// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bonds.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createBondDetails = `-- name: CreateBondDetails :one
INSERT INTO bond_details (
    investment_id, bond_type, issuer, face_value,
    coupon_rate, coupon_frequency, maturity_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING investment_id, bond_type, issuer, face_value, coupon_rate, coupon_frequency, maturity_date
`

type CreateBondDetailsParams struct {
	InvestmentID    uuid.UUID       `json:"investment_id"`
	BondType        string          `json:"bond_type"`
	Issuer          string          `json:"issuer"`
	FaceValue       decimal.Decimal `json:"face_value"`
	CouponRate      decimal.Decimal `json:"coupon_rate"`
	CouponFrequency string          `json:"coupon_frequency"`
	MaturityDate    time.Time       `json:"maturity_date"`
}

func (q *Queries) CreateBondDetails(ctx context.Context, arg CreateBondDetailsParams) (BondDetail, error) {
	row := q.db.QueryRow(ctx, createBondDetails,
		arg.InvestmentID,
		arg.BondType,
		arg.Issuer,
		arg.FaceValue,
		arg.CouponRate,
		arg.CouponFrequency,
		arg.MaturityDate,
	)
	var i BondDetail
	err := row.Scan(
		&i.InvestmentID,
		&i.BondType,
		&i.Issuer,
		&i.FaceValue,
		&i.CouponRate,
		&i.CouponFrequency,
		&i.MaturityDate,
	)
	return i, err
}

const getBondDetailsByInvestmentID = `-- name: GetBondDetailsByInvestmentID :one
SELECT investment_id, bond_type, issuer, face_value, coupon_rate, coupon_frequency, maturity_date
FROM bond_details
WHERE investment_id = $1
`

func (q *Queries) GetBondDetailsByInvestmentID(ctx context.Context, investmentID uuid.UUID) (BondDetail, error) {
	row := q.db.QueryRow(ctx, getBondDetailsByInvestmentID, investmentID)
	var i BondDetail
	err := row.Scan(
		&i.InvestmentID,
		&i.BondType,
		&i.Issuer,
		&i.FaceValue,
		&i.CouponRate,
		&i.CouponFrequency,
		&i.MaturityDate,
	)
	return i, err
}

const listBondDetailsByInvestmentIDs = `-- name: ListBondDetailsByInvestmentIDs :many
SELECT investment_id, bond_type, issuer, face_value, coupon_rate, coupon_frequency, maturity_date
FROM bond_details
WHERE investment_id = ANY($1::uuid[])
`

func (q *Queries) ListBondDetailsByInvestmentIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]BondDetail, error) {
	rows, err := q.db.Query(ctx, listBondDetailsByInvestmentIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BondDetail
	for rows.Next() {
		var i BondDetail
		if err := rows.Scan(
			&i.InvestmentID,
			&i.BondType,
			&i.Issuer,
			&i.FaceValue,
			&i.CouponRate,
			&i.CouponFrequency,
			&i.MaturityDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBondDetails = `-- name: UpdateBondDetails :one
UPDATE bond_details
SET bond_type        = $2,
    issuer           = $3,
    face_value       = $4,
    coupon_rate      = $5,
    coupon_frequency = $6,
    maturity_date    = $7
WHERE investment_id = $1
RETURNING investment_id, bond_type, issuer, face_value, coupon_rate, coupon_frequency, maturity_date
`

type UpdateBondDetailsParams struct {
	InvestmentID    uuid.UUID       `json:"investment_id"`
	BondType        string          `json:"bond_type"`
	Issuer          string          `json:"issuer"`
	FaceValue       decimal.Decimal `json:"face_value"`
	CouponRate      decimal.Decimal `json:"coupon_rate"`
	CouponFrequency string          `json:"coupon_frequency"`
	MaturityDate    time.Time       `json:"maturity_date"`
}

func (q *Queries) UpdateBondDetails(ctx context.Context, arg UpdateBondDetailsParams) (BondDetail, error) {
	row := q.db.QueryRow(ctx, updateBondDetails,
		arg.InvestmentID,
		arg.BondType,
		arg.Issuer,
		arg.FaceValue,
		arg.CouponRate,
		arg.CouponFrequency,
		arg.MaturityDate,
	)
	var i BondDetail
	err := row.Scan(
		&i.InvestmentID,
		&i.BondType,
		&i.Issuer,
		&i.FaceValue,
		&i.CouponRate,
		&i.CouponFrequency,
		&i.MaturityDate,
	)
	return i, err
}
