// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fx_rates.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createFxRate = `-- name: CreateFxRate :one

INSERT INTO fx_rates (
    household_id, year_month, currency, rate, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $5
)
RETURNING id, household_id, year_month, currency, rate, created_by, created_at, updated_by, updated_at, deleted_at
`

type CreateFxRateParams struct {
	HouseholdID uuid.UUID       `json:"household_id"`
	YearMonth   time.Time       `json:"year_month"`
	Currency    string          `json:"currency"`
	Rate        decimal.Decimal `json:"rate"`
	CreatedBy   *uuid.UUID      `json:"created_by"`
}

// Manual monthly FX rates (ADR-0002). Household-scoped; `rate` is reporting-
// currency units per 1 unit of `currency`. year_month + currency are the
// identity (one rate per month per currency) — to change those, delete and
// recreate; UpdateFxRate edits only the rate.
func (q *Queries) CreateFxRate(ctx context.Context, arg CreateFxRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, createFxRate,
		arg.HouseholdID,
		arg.YearMonth,
		arg.Currency,
		arg.Rate,
		arg.CreatedBy,
	)
	var i FxRate
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.YearMonth,
		&i.Currency,
		&i.Rate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFxRateByID = `-- name: GetFxRateByID :one
SELECT id, household_id, year_month, currency, rate, created_by, created_at, updated_by, updated_at, deleted_at
FROM fx_rates
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type GetFxRateByIDParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetFxRateByID(ctx context.Context, arg GetFxRateByIDParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, getFxRateByID, arg.ID, arg.HouseholdID)
	var i FxRate
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.YearMonth,
		&i.Currency,
		&i.Rate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listFxRatesByHousehold = `-- name: ListFxRatesByHousehold :many
SELECT id, household_id, year_month, currency, rate, created_by, created_at, updated_by, updated_at, deleted_at
FROM fx_rates
WHERE household_id = $1 AND deleted_at IS NULL
ORDER BY year_month DESC, currency ASC
`

func (q *Queries) ListFxRatesByHousehold(ctx context.Context, householdID uuid.UUID) ([]FxRate, error) {
	rows, err := q.db.Query(ctx, listFxRatesByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FxRate
	for rows.Next() {
		var i FxRate
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.YearMonth,
			&i.Currency,
			&i.Rate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFxRate = `-- name: SoftDeleteFxRate :execrows
UPDATE fx_rates
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type SoftDeleteFxRateParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteFxRate(ctx context.Context, arg SoftDeleteFxRateParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteFxRate, arg.ID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFxRate = `-- name: UpdateFxRate :one
UPDATE fx_rates
SET rate       = $3,
    updated_by = $4,
    updated_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
RETURNING id, household_id, year_month, currency, rate, created_by, created_at, updated_by, updated_at, deleted_at
`

type UpdateFxRateParams struct {
	ID          uuid.UUID       `json:"id"`
	HouseholdID uuid.UUID       `json:"household_id"`
	Rate        decimal.Decimal `json:"rate"`
	UpdatedBy   *uuid.UUID      `json:"updated_by"`
}

func (q *Queries) UpdateFxRate(ctx context.Context, arg UpdateFxRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, updateFxRate,
		arg.ID,
		arg.HouseholdID,
		arg.Rate,
		arg.UpdatedBy,
	)
	var i FxRate
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.YearMonth,
		&i.Currency,
		&i.Rate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
