// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: golds.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createGoldDetails = `-- name: CreateGoldDetails :one
INSERT INTO gold_details (
    investment_id, form, purity
) VALUES (
    $1, $2, $3
)
RETURNING investment_id, form, purity
`

type CreateGoldDetailsParams struct {
	InvestmentID uuid.UUID       `json:"investment_id"`
	Form         string          `json:"form"`
	Purity       decimal.Decimal `json:"purity"`
}

func (q *Queries) CreateGoldDetails(ctx context.Context, arg CreateGoldDetailsParams) (GoldDetail, error) {
	row := q.db.QueryRow(ctx, createGoldDetails, arg.InvestmentID, arg.Form, arg.Purity)
	var i GoldDetail
	err := row.Scan(&i.InvestmentID, &i.Form, &i.Purity)
	return i, err
}

const getGoldDetailsByInvestmentID = `-- name: GetGoldDetailsByInvestmentID :one
SELECT investment_id, form, purity
FROM gold_details
WHERE investment_id = $1
`

func (q *Queries) GetGoldDetailsByInvestmentID(ctx context.Context, investmentID uuid.UUID) (GoldDetail, error) {
	row := q.db.QueryRow(ctx, getGoldDetailsByInvestmentID, investmentID)
	var i GoldDetail
	err := row.Scan(&i.InvestmentID, &i.Form, &i.Purity)
	return i, err
}

const listGoldDetailsByInvestmentIDs = `-- name: ListGoldDetailsByInvestmentIDs :many
SELECT investment_id, form, purity
FROM gold_details
WHERE investment_id = ANY($1::uuid[])
`

func (q *Queries) ListGoldDetailsByInvestmentIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GoldDetail, error) {
	rows, err := q.db.Query(ctx, listGoldDetailsByInvestmentIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoldDetail
	for rows.Next() {
		var i GoldDetail
		if err := rows.Scan(&i.InvestmentID, &i.Form, &i.Purity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoldDetails = `-- name: UpdateGoldDetails :one
UPDATE gold_details
SET form   = $2,
    purity = $3
WHERE investment_id = $1
RETURNING investment_id, form, purity
`

type UpdateGoldDetailsParams struct {
	InvestmentID uuid.UUID       `json:"investment_id"`
	Form         string          `json:"form"`
	Purity       decimal.Decimal `json:"purity"`
}

func (q *Queries) UpdateGoldDetails(ctx context.Context, arg UpdateGoldDetailsParams) (GoldDetail, error) {
	row := q.db.QueryRow(ctx, updateGoldDetails, arg.InvestmentID, arg.Form, arg.Purity)
	var i GoldDetail
	err := row.Scan(&i.InvestmentID, &i.Form, &i.Purity)
	return i, err
}
