// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: households.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createHousehold = `-- name: CreateHousehold :one
INSERT INTO households (
    display_name, reporting_currency
) VALUES (
    $1, $2
)
RETURNING id, display_name, reporting_currency, created_by, created_at, updated_by, updated_at, deleted_at
`

type CreateHouseholdParams struct {
	DisplayName       string `json:"display_name"`
	ReportingCurrency string `json:"reporting_currency"`
}

func (q *Queries) CreateHousehold(ctx context.Context, arg CreateHouseholdParams) (Household, error) {
	row := q.db.QueryRow(ctx, createHousehold, arg.DisplayName, arg.ReportingCurrency)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.ReportingCurrency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getHouseholdByID = `-- name: GetHouseholdByID :one
SELECT id, display_name, reporting_currency, created_by, created_at, updated_by, updated_at, deleted_at
FROM households
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetHouseholdByID(ctx context.Context, id uuid.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByID, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.ReportingCurrency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
