// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: income.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createIncome = `-- name: CreateIncome :one
INSERT INTO income (
    household_id, date, amount, currency, category, description,
    ownership_type, sole_owner_user_id,
    created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $9
)
RETURNING id, household_id, date, amount, currency, category, description, ownership_type, sole_owner_user_id, created_by, created_at, updated_by, updated_at, deleted_at
`

type CreateIncomeParams struct {
	HouseholdID     uuid.UUID       `json:"household_id"`
	Date            time.Time       `json:"date"`
	Amount          decimal.Decimal `json:"amount"`
	Currency        string          `json:"currency"`
	Category        string          `json:"category"`
	Description     *string         `json:"description"`
	OwnershipType   string          `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID      `json:"sole_owner_user_id"`
	CreatedBy       *uuid.UUID      `json:"created_by"`
}

func (q *Queries) CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, createIncome,
		arg.HouseholdID,
		arg.Date,
		arg.Amount,
		arg.Currency,
		arg.Category,
		arg.Description,
		arg.OwnershipType,
		arg.SoleOwnerUserID,
		arg.CreatedBy,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Date,
		&i.Amount,
		&i.Currency,
		&i.Category,
		&i.Description,
		&i.OwnershipType,
		&i.SoleOwnerUserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getIncomeByID = `-- name: GetIncomeByID :one
SELECT id, household_id, date, amount, currency, category, description, ownership_type, sole_owner_user_id, created_by, created_at, updated_by, updated_at, deleted_at
FROM income
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type GetIncomeByIDParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetIncomeByID(ctx context.Context, arg GetIncomeByIDParams) (Income, error) {
	row := q.db.QueryRow(ctx, getIncomeByID, arg.ID, arg.HouseholdID)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Date,
		&i.Amount,
		&i.Currency,
		&i.Category,
		&i.Description,
		&i.OwnershipType,
		&i.SoleOwnerUserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listIncomeByHousehold = `-- name: ListIncomeByHousehold :many
SELECT id, household_id, date, amount, currency, category, description, ownership_type, sole_owner_user_id, created_by, created_at, updated_by, updated_at, deleted_at
FROM income
WHERE household_id = $1
  AND deleted_at IS NULL
ORDER BY date DESC, created_at DESC
`

func (q *Queries) ListIncomeByHousehold(ctx context.Context, householdID uuid.UUID) ([]Income, error) {
	rows, err := q.db.Query(ctx, listIncomeByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Income
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Date,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.Description,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteIncome = `-- name: SoftDeleteIncome :execrows
UPDATE income
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type SoftDeleteIncomeParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteIncome(ctx context.Context, arg SoftDeleteIncomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteIncome, arg.ID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIncome = `-- name: UpdateIncome :one
UPDATE income
SET date               = $3,
    amount             = $4,
    currency           = $5,
    category           = $6,
    description        = $7,
    ownership_type     = $8,
    sole_owner_user_id = $9,
    updated_by         = $10,
    updated_at         = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
RETURNING id, household_id, date, amount, currency, category, description, ownership_type, sole_owner_user_id, created_by, created_at, updated_by, updated_at, deleted_at
`

type UpdateIncomeParams struct {
	ID              uuid.UUID       `json:"id"`
	HouseholdID     uuid.UUID       `json:"household_id"`
	Date            time.Time       `json:"date"`
	Amount          decimal.Decimal `json:"amount"`
	Currency        string          `json:"currency"`
	Category        string          `json:"category"`
	Description     *string         `json:"description"`
	OwnershipType   string          `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID      `json:"sole_owner_user_id"`
	UpdatedBy       *uuid.UUID      `json:"updated_by"`
}

func (q *Queries) UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, updateIncome,
		arg.ID,
		arg.HouseholdID,
		arg.Date,
		arg.Amount,
		arg.Currency,
		arg.Category,
		arg.Description,
		arg.OwnershipType,
		arg.SoleOwnerUserID,
		arg.UpdatedBy,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Date,
		&i.Amount,
		&i.Currency,
		&i.Category,
		&i.Description,
		&i.OwnershipType,
		&i.SoleOwnerUserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
