// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: investments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createInvestment = `-- name: CreateInvestment :one
INSERT INTO investments (
    household_id, display_name, description, subtype,
    ownership_type, sole_owner_user_id, native_currency,
    created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $8
)
RETURNING id, household_id, display_name, description, subtype, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, created_by, created_at, updated_by, updated_at, deleted_at
`

type CreateInvestmentParams struct {
	HouseholdID     uuid.UUID  `json:"household_id"`
	DisplayName     string     `json:"display_name"`
	Description     *string    `json:"description"`
	Subtype         string     `json:"subtype"`
	OwnershipType   string     `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID `json:"sole_owner_user_id"`
	NativeCurrency  string     `json:"native_currency"`
	CreatedBy       *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateInvestment(ctx context.Context, arg CreateInvestmentParams) (Investment, error) {
	row := q.db.QueryRow(ctx, createInvestment,
		arg.HouseholdID,
		arg.DisplayName,
		arg.Description,
		arg.Subtype,
		arg.OwnershipType,
		arg.SoleOwnerUserID,
		arg.NativeCurrency,
		arg.CreatedBy,
	)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Description,
		&i.Subtype,
		&i.OwnershipType,
		&i.SoleOwnerUserID,
		&i.NativeCurrency,
		&i.Status,
		&i.TerminatedAt,
		&i.TerminationNote,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInvestmentByID = `-- name: GetInvestmentByID :one
SELECT id, household_id, display_name, description, subtype, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, created_by, created_at, updated_by, updated_at, deleted_at
FROM investments
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type GetInvestmentByIDParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetInvestmentByID(ctx context.Context, arg GetInvestmentByIDParams) (Investment, error) {
	row := q.db.QueryRow(ctx, getInvestmentByID, arg.ID, arg.HouseholdID)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Description,
		&i.Subtype,
		&i.OwnershipType,
		&i.SoleOwnerUserID,
		&i.NativeCurrency,
		&i.Status,
		&i.TerminatedAt,
		&i.TerminationNote,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listInvestmentsByHousehold = `-- name: ListInvestmentsByHousehold :many
SELECT id, household_id, display_name, description, subtype, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, created_by, created_at, updated_by, updated_at, deleted_at
FROM investments
WHERE household_id = $1
  AND ($2::text IS NULL OR subtype = $2::text)
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListInvestmentsByHouseholdParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	Subtype     *string   `json:"subtype"`
}

func (q *Queries) ListInvestmentsByHousehold(ctx context.Context, arg ListInvestmentsByHouseholdParams) ([]Investment, error) {
	rows, err := q.db.Query(ctx, listInvestmentsByHousehold, arg.HouseholdID, arg.Subtype)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Investment
	for rows.Next() {
		var i Investment
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.DisplayName,
			&i.Description,
			&i.Subtype,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
			&i.NativeCurrency,
			&i.Status,
			&i.TerminatedAt,
			&i.TerminationNote,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteInvestment = `-- name: SoftDeleteInvestment :execrows
UPDATE investments
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type SoftDeleteInvestmentParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteInvestment(ctx context.Context, arg SoftDeleteInvestmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteInvestment, arg.ID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInvestment = `-- name: UpdateInvestment :one
UPDATE investments
SET display_name       = $3,
    description        = $4,
    ownership_type     = $5,
    sole_owner_user_id = $6,
    updated_by         = $7,
    updated_at         = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
RETURNING id, household_id, display_name, description, subtype, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, created_by, created_at, updated_by, updated_at, deleted_at
`

type UpdateInvestmentParams struct {
	ID              uuid.UUID  `json:"id"`
	HouseholdID     uuid.UUID  `json:"household_id"`
	DisplayName     string     `json:"display_name"`
	Description     *string    `json:"description"`
	OwnershipType   string     `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID `json:"sole_owner_user_id"`
	UpdatedBy       *uuid.UUID `json:"updated_by"`
}

func (q *Queries) UpdateInvestment(ctx context.Context, arg UpdateInvestmentParams) (Investment, error) {
	row := q.db.QueryRow(ctx, updateInvestment,
		arg.ID,
		arg.HouseholdID,
		arg.DisplayName,
		arg.Description,
		arg.OwnershipType,
		arg.SoleOwnerUserID,
		arg.UpdatedBy,
	)
	var i Investment
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Description,
		&i.Subtype,
		&i.OwnershipType,
		&i.SoleOwnerUserID,
		&i.NativeCurrency,
		&i.Status,
		&i.TerminatedAt,
		&i.TerminationNote,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
