// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: investment_snapshots.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createInvestmentSnapshot = `-- name: CreateInvestmentSnapshot :one

WITH owned_investment AS (
    SELECT i.id AS iid
    FROM investments i
    WHERE i.id = $1 AND i.household_id = $11::uuid AND i.deleted_at IS NULL
)
INSERT INTO investment_snapshots (
    investment_id, year_month, amount, currency,
    quantity, price_per_unit, accrued_interest,
    as_of_date, description,
    created_by, updated_by
)
SELECT owned_investment.iid, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10
FROM owned_investment
RETURNING id, investment_id, year_month, amount, currency, quantity, price_per_unit, accrued_interest, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
`

type CreateInvestmentSnapshotParams struct {
	ID              uuid.UUID        `json:"id"`
	YearMonth       time.Time        `json:"year_month"`
	Amount          decimal.Decimal  `json:"amount"`
	Currency        string           `json:"currency"`
	Quantity        *decimal.Decimal `json:"quantity"`
	PricePerUnit    *decimal.Decimal `json:"price_per_unit"`
	AccruedInterest *decimal.Decimal `json:"accrued_interest"`
	AsOfDate        *time.Time       `json:"as_of_date"`
	Description     *string          `json:"description"`
	CreatedBy       *uuid.UUID       `json:"created_by"`
	HouseholdID     uuid.UUID        `json:"household_id"`
}

// All snapshot queries verify the parent investment belongs to the requesting
// Household. This is belt + suspenders on top of the application-layer
// tenancy middleware: even if a handler forgets to filter, SQL will not
// expose or mutate snapshots from another Household. The XOR shape
// (quantity+price vs accrued_interest) is enforced at the column level by
// the table's CHECK constraint and at the subtype level by the repository
// (per ADR-0022).
func (q *Queries) CreateInvestmentSnapshot(ctx context.Context, arg CreateInvestmentSnapshotParams) (InvestmentSnapshot, error) {
	row := q.db.QueryRow(ctx, createInvestmentSnapshot,
		arg.ID,
		arg.YearMonth,
		arg.Amount,
		arg.Currency,
		arg.Quantity,
		arg.PricePerUnit,
		arg.AccruedInterest,
		arg.AsOfDate,
		arg.Description,
		arg.CreatedBy,
		arg.HouseholdID,
	)
	var i InvestmentSnapshot
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.Quantity,
		&i.PricePerUnit,
		&i.AccruedInterest,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInvestmentSnapshotByID = `-- name: GetInvestmentSnapshotByID :one
SELECT s.id, s.investment_id, s.year_month, s.amount, s.currency, s.quantity, s.price_per_unit, s.accrued_interest, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM investment_snapshots s
JOIN investments i ON i.id = s.investment_id
WHERE s.id = $1
  AND i.household_id = $2
  AND i.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type GetInvestmentSnapshotByIDParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetInvestmentSnapshotByID(ctx context.Context, arg GetInvestmentSnapshotByIDParams) (InvestmentSnapshot, error) {
	row := q.db.QueryRow(ctx, getInvestmentSnapshotByID, arg.ID, arg.HouseholdID)
	var i InvestmentSnapshot
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.Quantity,
		&i.PricePerUnit,
		&i.AccruedInterest,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listInvestmentSnapshotsForInvestment = `-- name: ListInvestmentSnapshotsForInvestment :many
SELECT s.id, s.investment_id, s.year_month, s.amount, s.currency, s.quantity, s.price_per_unit, s.accrued_interest, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
FROM investment_snapshots s
JOIN investments i ON i.id = s.investment_id
WHERE s.investment_id = $1
  AND i.household_id = $2
  AND i.deleted_at IS NULL
  AND s.deleted_at IS NULL
ORDER BY s.year_month DESC
`

type ListInvestmentSnapshotsForInvestmentParams struct {
	InvestmentID uuid.UUID `json:"investment_id"`
	HouseholdID  uuid.UUID `json:"household_id"`
}

func (q *Queries) ListInvestmentSnapshotsForInvestment(ctx context.Context, arg ListInvestmentSnapshotsForInvestmentParams) ([]InvestmentSnapshot, error) {
	rows, err := q.db.Query(ctx, listInvestmentSnapshotsForInvestment, arg.InvestmentID, arg.HouseholdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvestmentSnapshot
	for rows.Next() {
		var i InvestmentSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.InvestmentID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.Quantity,
			&i.PricePerUnit,
			&i.AccruedInterest,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestInvestmentSnapshotsByInvestmentIDs = `-- name: ListLatestInvestmentSnapshotsByInvestmentIDs :many
SELECT DISTINCT ON (investment_id) id, investment_id, year_month, amount, currency, quantity, price_per_unit, accrued_interest, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
FROM investment_snapshots
WHERE investment_id = ANY($1::uuid[]) AND deleted_at IS NULL
ORDER BY investment_id, year_month DESC
`

// Batch fetch of the most-recent snapshot per investment, for list views.
func (q *Queries) ListLatestInvestmentSnapshotsByInvestmentIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]InvestmentSnapshot, error) {
	rows, err := q.db.Query(ctx, listLatestInvestmentSnapshotsByInvestmentIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvestmentSnapshot
	for rows.Next() {
		var i InvestmentSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.InvestmentID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.Quantity,
			&i.PricePerUnit,
			&i.AccruedInterest,
			&i.AsOfDate,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteInvestmentSnapshot = `-- name: SoftDeleteInvestmentSnapshot :execrows
UPDATE investment_snapshots s
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
FROM investments i
WHERE s.id = $1
  AND s.investment_id = i.id
  AND i.household_id = $2
  AND i.deleted_at IS NULL
  AND s.deleted_at IS NULL
`

type SoftDeleteInvestmentSnapshotParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteInvestmentSnapshot(ctx context.Context, arg SoftDeleteInvestmentSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteInvestmentSnapshot, arg.ID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInvestmentSnapshot = `-- name: UpdateInvestmentSnapshot :one
UPDATE investment_snapshots s
SET amount           = $3,
    currency         = $4,
    quantity         = $5,
    price_per_unit   = $6,
    accrued_interest = $7,
    as_of_date       = $8,
    description      = $9,
    updated_by       = $10,
    updated_at       = now()
FROM investments i
WHERE s.id = $1
  AND s.investment_id = i.id
  AND i.household_id = $2
  AND i.deleted_at IS NULL
  AND s.deleted_at IS NULL
RETURNING s.id, s.investment_id, s.year_month, s.amount, s.currency, s.quantity, s.price_per_unit, s.accrued_interest, s.as_of_date, s.description, s.created_by, s.created_at, s.updated_by, s.updated_at, s.deleted_at
`

type UpdateInvestmentSnapshotParams struct {
	ID              uuid.UUID        `json:"id"`
	HouseholdID     uuid.UUID        `json:"household_id"`
	Amount          decimal.Decimal  `json:"amount"`
	Currency        string           `json:"currency"`
	Quantity        *decimal.Decimal `json:"quantity"`
	PricePerUnit    *decimal.Decimal `json:"price_per_unit"`
	AccruedInterest *decimal.Decimal `json:"accrued_interest"`
	AsOfDate        *time.Time       `json:"as_of_date"`
	Description     *string          `json:"description"`
	UpdatedBy       *uuid.UUID       `json:"updated_by"`
}

func (q *Queries) UpdateInvestmentSnapshot(ctx context.Context, arg UpdateInvestmentSnapshotParams) (InvestmentSnapshot, error) {
	row := q.db.QueryRow(ctx, updateInvestmentSnapshot,
		arg.ID,
		arg.HouseholdID,
		arg.Amount,
		arg.Currency,
		arg.Quantity,
		arg.PricePerUnit,
		arg.AccruedInterest,
		arg.AsOfDate,
		arg.Description,
		arg.UpdatedBy,
	)
	var i InvestmentSnapshot
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.Quantity,
		&i.PricePerUnit,
		&i.AccruedInterest,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertInvestmentSnapshot = `-- name: UpsertInvestmentSnapshot :one
WITH owned_investment AS (
    SELECT i.id AS iid
    FROM investments i
    WHERE i.id = $1 AND i.household_id = $11::uuid AND i.deleted_at IS NULL
)
INSERT INTO investment_snapshots (
    investment_id, year_month, amount, currency,
    quantity, price_per_unit, accrued_interest,
    as_of_date, description,
    created_by, updated_by
)
SELECT owned_investment.iid, $2, $3, $4, $5, $6, $7, $8, $9, $10, $10
FROM owned_investment
ON CONFLICT (investment_id, year_month) WHERE deleted_at IS NULL
DO UPDATE SET
    amount           = EXCLUDED.amount,
    currency         = EXCLUDED.currency,
    quantity         = EXCLUDED.quantity,
    price_per_unit   = EXCLUDED.price_per_unit,
    accrued_interest = EXCLUDED.accrued_interest,
    as_of_date       = EXCLUDED.as_of_date,
    description      = EXCLUDED.description,
    updated_by       = EXCLUDED.updated_by,
    updated_at       = now()
RETURNING id, investment_id, year_month, amount, currency, quantity, price_per_unit, accrued_interest, as_of_date, description, created_by, created_at, updated_by, updated_at, deleted_at
`

type UpsertInvestmentSnapshotParams struct {
	ID              uuid.UUID        `json:"id"`
	YearMonth       time.Time        `json:"year_month"`
	Amount          decimal.Decimal  `json:"amount"`
	Currency        string           `json:"currency"`
	Quantity        *decimal.Decimal `json:"quantity"`
	PricePerUnit    *decimal.Decimal `json:"price_per_unit"`
	AccruedInterest *decimal.Decimal `json:"accrued_interest"`
	AsOfDate        *time.Time       `json:"as_of_date"`
	Description     *string          `json:"description"`
	CreatedBy       *uuid.UUID       `json:"created_by"`
	HouseholdID     uuid.UUID        `json:"household_id"`
}

// UpsertInvestmentSnapshot inserts a snapshot or, when one already exists for
// the (investment_id, year_month) pair, overwrites it (last-write-wins) — the
// importer needs idempotent re-runs of a multi-year backfill. ON CONFLICT
// targets the partial unique index, so its predicate (deleted_at IS NULL) is
// repeated. The repo validates the value-column shape against the parent's
// subtype before calling this; the DB CHECK is the final backstop.
// created_by is only set on insert; updated_by always.
func (q *Queries) UpsertInvestmentSnapshot(ctx context.Context, arg UpsertInvestmentSnapshotParams) (InvestmentSnapshot, error) {
	row := q.db.QueryRow(ctx, upsertInvestmentSnapshot,
		arg.ID,
		arg.YearMonth,
		arg.Amount,
		arg.Currency,
		arg.Quantity,
		arg.PricePerUnit,
		arg.AccruedInterest,
		arg.AsOfDate,
		arg.Description,
		arg.CreatedBy,
		arg.HouseholdID,
	)
	var i InvestmentSnapshot
	err := row.Scan(
		&i.ID,
		&i.InvestmentID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.Quantity,
		&i.PricePerUnit,
		&i.AccruedInterest,
		&i.AsOfDate,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
