// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO household_invitations (
    household_id, invited_email, token, created_by, expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, household_id, invited_email, token, created_by, created_at, expires_at, used_at
`

type CreateInvitationParams struct {
	HouseholdID  uuid.UUID          `json:"household_id"`
	InvitedEmail string             `json:"invited_email"`
	Token        string             `json:"token"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (HouseholdInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.HouseholdID,
		arg.InvitedEmail,
		arg.Token,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i HouseholdInvitation
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.InvitedEmail,
		&i.Token,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, household_id, invited_email, token, created_by, created_at, expires_at, used_at
FROM household_invitations
WHERE token = $1
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (HouseholdInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i HouseholdInvitation
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.InvitedEmail,
		&i.Token,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const markInvitationUsed = `-- name: MarkInvitationUsed :exec
UPDATE household_invitations
SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkInvitationUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInvitationUsed, id)
	return err
}
