// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: liabilities.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createLiability = `-- name: CreateLiability :one
INSERT INTO liabilities (
    household_id, display_name, description, subtype,
    ownership_type, sole_owner_user_id, native_currency,
    counterparty_name, principal, interest_rate,
    term_months, start_date, maturity_date,
    created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $14
)
RETURNING id, household_id, display_name, description, subtype, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, counterparty_name, principal, interest_rate, term_months, start_date, maturity_date, created_by, created_at, updated_by, updated_at, deleted_at
`

type CreateLiabilityParams struct {
	HouseholdID      uuid.UUID        `json:"household_id"`
	DisplayName      string           `json:"display_name"`
	Description      *string          `json:"description"`
	Subtype          string           `json:"subtype"`
	OwnershipType    string           `json:"ownership_type"`
	SoleOwnerUserID  *uuid.UUID       `json:"sole_owner_user_id"`
	NativeCurrency   string           `json:"native_currency"`
	CounterpartyName string           `json:"counterparty_name"`
	Principal        *decimal.Decimal `json:"principal"`
	InterestRate     *decimal.Decimal `json:"interest_rate"`
	TermMonths       *int32           `json:"term_months"`
	StartDate        *time.Time       `json:"start_date"`
	MaturityDate     *time.Time       `json:"maturity_date"`
	CreatedBy        *uuid.UUID       `json:"created_by"`
}

func (q *Queries) CreateLiability(ctx context.Context, arg CreateLiabilityParams) (Liability, error) {
	row := q.db.QueryRow(ctx, createLiability,
		arg.HouseholdID,
		arg.DisplayName,
		arg.Description,
		arg.Subtype,
		arg.OwnershipType,
		arg.SoleOwnerUserID,
		arg.NativeCurrency,
		arg.CounterpartyName,
		arg.Principal,
		arg.InterestRate,
		arg.TermMonths,
		arg.StartDate,
		arg.MaturityDate,
		arg.CreatedBy,
	)
	var i Liability
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Description,
		&i.Subtype,
		&i.OwnershipType,
		&i.SoleOwnerUserID,
		&i.NativeCurrency,
		&i.Status,
		&i.TerminatedAt,
		&i.TerminationNote,
		&i.CounterpartyName,
		&i.Principal,
		&i.InterestRate,
		&i.TermMonths,
		&i.StartDate,
		&i.MaturityDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLiabilityByID = `-- name: GetLiabilityByID :one
SELECT id, household_id, display_name, description, subtype, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, counterparty_name, principal, interest_rate, term_months, start_date, maturity_date, created_by, created_at, updated_by, updated_at, deleted_at
FROM liabilities
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type GetLiabilityByIDParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetLiabilityByID(ctx context.Context, arg GetLiabilityByIDParams) (Liability, error) {
	row := q.db.QueryRow(ctx, getLiabilityByID, arg.ID, arg.HouseholdID)
	var i Liability
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Description,
		&i.Subtype,
		&i.OwnershipType,
		&i.SoleOwnerUserID,
		&i.NativeCurrency,
		&i.Status,
		&i.TerminatedAt,
		&i.TerminationNote,
		&i.CounterpartyName,
		&i.Principal,
		&i.InterestRate,
		&i.TermMonths,
		&i.StartDate,
		&i.MaturityDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listLiabilitiesByHousehold = `-- name: ListLiabilitiesByHousehold :many
SELECT id, household_id, display_name, description, subtype, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, counterparty_name, principal, interest_rate, term_months, start_date, maturity_date, created_by, created_at, updated_by, updated_at, deleted_at
FROM liabilities
WHERE household_id = $1
  AND ($2::text IS NULL OR subtype = $2::text)
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListLiabilitiesByHouseholdParams struct {
	HouseholdID uuid.UUID `json:"household_id"`
	Subtype     *string   `json:"subtype"`
}

func (q *Queries) ListLiabilitiesByHousehold(ctx context.Context, arg ListLiabilitiesByHouseholdParams) ([]Liability, error) {
	rows, err := q.db.Query(ctx, listLiabilitiesByHousehold, arg.HouseholdID, arg.Subtype)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Liability
	for rows.Next() {
		var i Liability
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.DisplayName,
			&i.Description,
			&i.Subtype,
			&i.OwnershipType,
			&i.SoleOwnerUserID,
			&i.NativeCurrency,
			&i.Status,
			&i.TerminatedAt,
			&i.TerminationNote,
			&i.CounterpartyName,
			&i.Principal,
			&i.InterestRate,
			&i.TermMonths,
			&i.StartDate,
			&i.MaturityDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLiability = `-- name: SoftDeleteLiability :execrows
UPDATE liabilities
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type SoftDeleteLiabilityParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteLiability(ctx context.Context, arg SoftDeleteLiabilityParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteLiability, arg.ID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLiability = `-- name: UpdateLiability :one
UPDATE liabilities
SET display_name       = $3,
    description        = $4,
    ownership_type     = $5,
    sole_owner_user_id = $6,
    counterparty_name  = $7,
    principal          = $8,
    interest_rate      = $9,
    term_months        = $10,
    start_date         = $11,
    maturity_date      = $12,
    updated_by         = $13,
    updated_at         = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
RETURNING id, household_id, display_name, description, subtype, ownership_type, sole_owner_user_id, native_currency, status, terminated_at, termination_note, counterparty_name, principal, interest_rate, term_months, start_date, maturity_date, created_by, created_at, updated_by, updated_at, deleted_at
`

type UpdateLiabilityParams struct {
	ID               uuid.UUID        `json:"id"`
	HouseholdID      uuid.UUID        `json:"household_id"`
	DisplayName      string           `json:"display_name"`
	Description      *string          `json:"description"`
	OwnershipType    string           `json:"ownership_type"`
	SoleOwnerUserID  *uuid.UUID       `json:"sole_owner_user_id"`
	CounterpartyName string           `json:"counterparty_name"`
	Principal        *decimal.Decimal `json:"principal"`
	InterestRate     *decimal.Decimal `json:"interest_rate"`
	TermMonths       *int32           `json:"term_months"`
	StartDate        *time.Time       `json:"start_date"`
	MaturityDate     *time.Time       `json:"maturity_date"`
	UpdatedBy        *uuid.UUID       `json:"updated_by"`
}

func (q *Queries) UpdateLiability(ctx context.Context, arg UpdateLiabilityParams) (Liability, error) {
	row := q.db.QueryRow(ctx, updateLiability,
		arg.ID,
		arg.HouseholdID,
		arg.DisplayName,
		arg.Description,
		arg.OwnershipType,
		arg.SoleOwnerUserID,
		arg.CounterpartyName,
		arg.Principal,
		arg.InterestRate,
		arg.TermMonths,
		arg.StartDate,
		arg.MaturityDate,
		arg.UpdatedBy,
	)
	var i Liability
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Description,
		&i.Subtype,
		&i.OwnershipType,
		&i.SoleOwnerUserID,
		&i.NativeCurrency,
		&i.Status,
		&i.TerminatedAt,
		&i.TerminationNote,
		&i.CounterpartyName,
		&i.Principal,
		&i.InterestRate,
		&i.TermMonths,
		&i.StartDate,
		&i.MaturityDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
