// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Asset struct {
	ID              uuid.UUID          `json:"id"`
	HouseholdID     uuid.UUID          `json:"household_id"`
	DisplayName     string             `json:"display_name"`
	Description     *string            `json:"description"`
	Subtype         string             `json:"subtype"`
	OwnershipType   string             `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID         `json:"sole_owner_user_id"`
	NativeCurrency  string             `json:"native_currency"`
	Status          string             `json:"status"`
	TerminatedAt    *time.Time         `json:"terminated_at"`
	TerminationNote *string            `json:"termination_note"`
	CreatedBy       *uuid.UUID         `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedBy       *uuid.UUID         `json:"updated_by"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type AssetSnapshot struct {
	ID          uuid.UUID          `json:"id"`
	AssetID     uuid.UUID          `json:"asset_id"`
	YearMonth   time.Time          `json:"year_month"`
	Amount      decimal.Decimal    `json:"amount"`
	Currency    string             `json:"currency"`
	AsOfDate    *time.Time         `json:"as_of_date"`
	Description *string            `json:"description"`
	CreatedBy   *uuid.UUID         `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedBy   *uuid.UUID         `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type BankAccountDetail struct {
	AssetID       uuid.UUID `json:"asset_id"`
	BankName      string    `json:"bank_name"`
	AccountNumber string    `json:"account_number"`
	AccountType   string    `json:"account_type"`
}

type GoldDetail struct {
	InvestmentID uuid.UUID       `json:"investment_id"`
	Form         string          `json:"form"`
	Purity       decimal.Decimal `json:"purity"`
}

type Household struct {
	ID                uuid.UUID          `json:"id"`
	DisplayName       string             `json:"display_name"`
	ReportingCurrency string             `json:"reporting_currency"`
	CreatedBy         *uuid.UUID         `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedBy         *uuid.UUID         `json:"updated_by"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type HouseholdInvitation struct {
	ID           uuid.UUID          `json:"id"`
	HouseholdID  uuid.UUID          `json:"household_id"`
	InvitedEmail string             `json:"invited_email"`
	Token        string             `json:"token"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	UsedAt       pgtype.Timestamptz `json:"used_at"`
}

type Investment struct {
	ID              uuid.UUID          `json:"id"`
	HouseholdID     uuid.UUID          `json:"household_id"`
	DisplayName     string             `json:"display_name"`
	Description     *string            `json:"description"`
	Subtype         string             `json:"subtype"`
	OwnershipType   string             `json:"ownership_type"`
	SoleOwnerUserID *uuid.UUID         `json:"sole_owner_user_id"`
	NativeCurrency  string             `json:"native_currency"`
	Status          string             `json:"status"`
	TerminatedAt    *time.Time         `json:"terminated_at"`
	TerminationNote *string            `json:"termination_note"`
	CreatedBy       *uuid.UUID         `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedBy       *uuid.UUID         `json:"updated_by"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type InvestmentSnapshot struct {
	ID              uuid.UUID          `json:"id"`
	InvestmentID    uuid.UUID          `json:"investment_id"`
	YearMonth       time.Time          `json:"year_month"`
	Amount          decimal.Decimal    `json:"amount"`
	Currency        string             `json:"currency"`
	Quantity        *decimal.Decimal   `json:"quantity"`
	PricePerUnit    *decimal.Decimal   `json:"price_per_unit"`
	AccruedInterest *decimal.Decimal   `json:"accrued_interest"`
	AsOfDate        *time.Time         `json:"as_of_date"`
	Description     *string            `json:"description"`
	CreatedBy       *uuid.UUID         `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedBy       *uuid.UUID         `json:"updated_by"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Liability struct {
	ID               uuid.UUID          `json:"id"`
	HouseholdID      uuid.UUID          `json:"household_id"`
	DisplayName      string             `json:"display_name"`
	Description      *string            `json:"description"`
	Subtype          string             `json:"subtype"`
	OwnershipType    string             `json:"ownership_type"`
	SoleOwnerUserID  *uuid.UUID         `json:"sole_owner_user_id"`
	NativeCurrency   string             `json:"native_currency"`
	Status           string             `json:"status"`
	TerminatedAt     *time.Time         `json:"terminated_at"`
	TerminationNote  *string            `json:"termination_note"`
	CounterpartyName string             `json:"counterparty_name"`
	Principal        *decimal.Decimal   `json:"principal"`
	InterestRate     *decimal.Decimal   `json:"interest_rate"`
	TermMonths       *int32             `json:"term_months"`
	StartDate        *time.Time         `json:"start_date"`
	MaturityDate     *time.Time         `json:"maturity_date"`
	CreatedBy        *uuid.UUID         `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedBy        *uuid.UUID         `json:"updated_by"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type LiabilitySnapshot struct {
	ID          uuid.UUID          `json:"id"`
	LiabilityID uuid.UUID          `json:"liability_id"`
	YearMonth   time.Time          `json:"year_month"`
	Amount      decimal.Decimal    `json:"amount"`
	Currency    string             `json:"currency"`
	AsOfDate    *time.Time         `json:"as_of_date"`
	Description *string            `json:"description"`
	CreatedBy   *uuid.UUID         `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedBy   *uuid.UUID         `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type MutualFundDetail struct {
	InvestmentID uuid.UUID `json:"investment_id"`
	FundCode     string    `json:"fund_code"`
	FundManager  *string   `json:"fund_manager"`
}

type PropertyDetail struct {
	AssetID                uuid.UUID        `json:"asset_id"`
	PropertyType           string           `json:"property_type"`
	Address                *string          `json:"address"`
	AcquisitionDate        *time.Time       `json:"acquisition_date"`
	AcquisitionCost        *decimal.Decimal `json:"acquisition_cost"`
	AnnualAmortizationRate *decimal.Decimal `json:"annual_amortization_rate"`
}

type Receivable struct {
	ID               uuid.UUID          `json:"id"`
	HouseholdID      uuid.UUID          `json:"household_id"`
	DisplayName      string             `json:"display_name"`
	Description      *string            `json:"description"`
	OwnershipType    string             `json:"ownership_type"`
	SoleOwnerUserID  *uuid.UUID         `json:"sole_owner_user_id"`
	NativeCurrency   string             `json:"native_currency"`
	Status           string             `json:"status"`
	TerminatedAt     *time.Time         `json:"terminated_at"`
	TerminationNote  *string            `json:"termination_note"`
	CounterpartyName string             `json:"counterparty_name"`
	DueDate          *time.Time         `json:"due_date"`
	CreatedBy        *uuid.UUID         `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedBy        *uuid.UUID         `json:"updated_by"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type ReceivableSnapshot struct {
	ID           uuid.UUID          `json:"id"`
	ReceivableID uuid.UUID          `json:"receivable_id"`
	YearMonth    time.Time          `json:"year_month"`
	Amount       decimal.Decimal    `json:"amount"`
	Currency     string             `json:"currency"`
	AsOfDate     *time.Time         `json:"as_of_date"`
	Description  *string            `json:"description"`
	CreatedBy    *uuid.UUID         `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedBy    *uuid.UUID         `json:"updated_by"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Session struct {
	ID         string             `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	UserAgent  *string            `json:"user_agent"`
}

type StockDetail struct {
	InvestmentID uuid.UUID `json:"investment_id"`
	Ticker       string    `json:"ticker"`
	Exchange     string    `json:"exchange"`
}

type User struct {
	ID          uuid.UUID          `json:"id"`
	HouseholdID uuid.UUID          `json:"household_id"`
	DisplayName string             `json:"display_name"`
	Email       string             `json:"email"`
	GoogleSub   string             `json:"google_sub"`
	Locale      string             `json:"locale"`
	TimeZone    string             `json:"time_zone"`
	CreatedBy   *uuid.UUID         `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedBy   *uuid.UUID         `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type VehicleDetail struct {
	AssetID                uuid.UUID        `json:"asset_id"`
	VehicleType            string           `json:"vehicle_type"`
	Make                   *string          `json:"make"`
	Model                  *string          `json:"model"`
	Year                   *int32           `json:"year"`
	PlateNumber            *string          `json:"plate_number"`
	AnnualDepreciationRate *decimal.Decimal `json:"annual_depreciation_rate"`
}
