// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Household struct {
	ID                uuid.UUID          `json:"id"`
	DisplayName       string             `json:"display_name"`
	ReportingCurrency string             `json:"reporting_currency"`
	CreatedBy         *uuid.UUID         `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedBy         *uuid.UUID         `json:"updated_by"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type HouseholdInvitation struct {
	ID           uuid.UUID          `json:"id"`
	HouseholdID  uuid.UUID          `json:"household_id"`
	InvitedEmail string             `json:"invited_email"`
	Token        string             `json:"token"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	UsedAt       pgtype.Timestamptz `json:"used_at"`
}

type Session struct {
	ID         string             `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	UserAgent  *string            `json:"user_agent"`
}

type User struct {
	ID          uuid.UUID          `json:"id"`
	HouseholdID uuid.UUID          `json:"household_id"`
	DisplayName string             `json:"display_name"`
	Email       string             `json:"email"`
	GoogleSub   string             `json:"google_sub"`
	Locale      string             `json:"locale"`
	TimeZone    string             `json:"time_zone"`
	CreatedBy   *uuid.UUID         `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedBy   *uuid.UUID         `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}
