// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: properties.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createPropertyDetails = `-- name: CreatePropertyDetails :one
INSERT INTO property_details (
    asset_id, property_type, address,
    acquisition_date, acquisition_cost, annual_amortization_rate
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING asset_id, property_type, address, acquisition_date, acquisition_cost, annual_amortization_rate
`

type CreatePropertyDetailsParams struct {
	AssetID                uuid.UUID        `json:"asset_id"`
	PropertyType           string           `json:"property_type"`
	Address                *string          `json:"address"`
	AcquisitionDate        *time.Time       `json:"acquisition_date"`
	AcquisitionCost        *decimal.Decimal `json:"acquisition_cost"`
	AnnualAmortizationRate *decimal.Decimal `json:"annual_amortization_rate"`
}

func (q *Queries) CreatePropertyDetails(ctx context.Context, arg CreatePropertyDetailsParams) (PropertyDetail, error) {
	row := q.db.QueryRow(ctx, createPropertyDetails,
		arg.AssetID,
		arg.PropertyType,
		arg.Address,
		arg.AcquisitionDate,
		arg.AcquisitionCost,
		arg.AnnualAmortizationRate,
	)
	var i PropertyDetail
	err := row.Scan(
		&i.AssetID,
		&i.PropertyType,
		&i.Address,
		&i.AcquisitionDate,
		&i.AcquisitionCost,
		&i.AnnualAmortizationRate,
	)
	return i, err
}

const getPropertyDetailsByAssetID = `-- name: GetPropertyDetailsByAssetID :one
SELECT asset_id, property_type, address, acquisition_date, acquisition_cost, annual_amortization_rate
FROM property_details
WHERE asset_id = $1
`

func (q *Queries) GetPropertyDetailsByAssetID(ctx context.Context, assetID uuid.UUID) (PropertyDetail, error) {
	row := q.db.QueryRow(ctx, getPropertyDetailsByAssetID, assetID)
	var i PropertyDetail
	err := row.Scan(
		&i.AssetID,
		&i.PropertyType,
		&i.Address,
		&i.AcquisitionDate,
		&i.AcquisitionCost,
		&i.AnnualAmortizationRate,
	)
	return i, err
}

const listPropertyDetailsByAssetIDs = `-- name: ListPropertyDetailsByAssetIDs :many
SELECT asset_id, property_type, address, acquisition_date, acquisition_cost, annual_amortization_rate
FROM property_details
WHERE asset_id = ANY($1::uuid[])
`

// Batch fetch — used to populate details for a list of assets in one query
// (avoids N+1 lookups when listing properties for a household).
func (q *Queries) ListPropertyDetailsByAssetIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]PropertyDetail, error) {
	rows, err := q.db.Query(ctx, listPropertyDetailsByAssetIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PropertyDetail
	for rows.Next() {
		var i PropertyDetail
		if err := rows.Scan(
			&i.AssetID,
			&i.PropertyType,
			&i.Address,
			&i.AcquisitionDate,
			&i.AcquisitionCost,
			&i.AnnualAmortizationRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePropertyDetails = `-- name: UpdatePropertyDetails :one
UPDATE property_details
SET property_type            = $2,
    address                  = $3,
    acquisition_date         = $4,
    acquisition_cost         = $5,
    annual_amortization_rate = $6
WHERE asset_id = $1
RETURNING asset_id, property_type, address, acquisition_date, acquisition_cost, annual_amortization_rate
`

type UpdatePropertyDetailsParams struct {
	AssetID                uuid.UUID        `json:"asset_id"`
	PropertyType           string           `json:"property_type"`
	Address                *string          `json:"address"`
	AcquisitionDate        *time.Time       `json:"acquisition_date"`
	AcquisitionCost        *decimal.Decimal `json:"acquisition_cost"`
	AnnualAmortizationRate *decimal.Decimal `json:"annual_amortization_rate"`
}

func (q *Queries) UpdatePropertyDetails(ctx context.Context, arg UpdatePropertyDetailsParams) (PropertyDetail, error) {
	row := q.db.QueryRow(ctx, updatePropertyDetails,
		arg.AssetID,
		arg.PropertyType,
		arg.Address,
		arg.AcquisitionDate,
		arg.AcquisitionCost,
		arg.AnnualAmortizationRate,
	)
	var i PropertyDetail
	err := row.Scan(
		&i.AssetID,
		&i.PropertyType,
		&i.Address,
		&i.AcquisitionDate,
		&i.AcquisitionCost,
		&i.AnnualAmortizationRate,
	)
	return i, err
}
