// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stocks.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createStockDetails = `-- name: CreateStockDetails :one
INSERT INTO stock_details (
    investment_id, ticker, exchange
) VALUES (
    $1, $2, $3
)
RETURNING investment_id, ticker, exchange
`

type CreateStockDetailsParams struct {
	InvestmentID uuid.UUID `json:"investment_id"`
	Ticker       string    `json:"ticker"`
	Exchange     string    `json:"exchange"`
}

func (q *Queries) CreateStockDetails(ctx context.Context, arg CreateStockDetailsParams) (StockDetail, error) {
	row := q.db.QueryRow(ctx, createStockDetails, arg.InvestmentID, arg.Ticker, arg.Exchange)
	var i StockDetail
	err := row.Scan(&i.InvestmentID, &i.Ticker, &i.Exchange)
	return i, err
}

const getStockDetailsByInvestmentID = `-- name: GetStockDetailsByInvestmentID :one
SELECT investment_id, ticker, exchange
FROM stock_details
WHERE investment_id = $1
`

func (q *Queries) GetStockDetailsByInvestmentID(ctx context.Context, investmentID uuid.UUID) (StockDetail, error) {
	row := q.db.QueryRow(ctx, getStockDetailsByInvestmentID, investmentID)
	var i StockDetail
	err := row.Scan(&i.InvestmentID, &i.Ticker, &i.Exchange)
	return i, err
}

const listStockDetailsByInvestmentIDs = `-- name: ListStockDetailsByInvestmentIDs :many
SELECT investment_id, ticker, exchange
FROM stock_details
WHERE investment_id = ANY($1::uuid[])
`

// Batch fetch — used to populate details for a list of investments in one
// query (avoids N+1 lookups when listing stocks for a household).
func (q *Queries) ListStockDetailsByInvestmentIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]StockDetail, error) {
	rows, err := q.db.Query(ctx, listStockDetailsByInvestmentIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockDetail
	for rows.Next() {
		var i StockDetail
		if err := rows.Scan(&i.InvestmentID, &i.Ticker, &i.Exchange); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStockDetails = `-- name: UpdateStockDetails :one
UPDATE stock_details
SET ticker   = $2,
    exchange = $3
WHERE investment_id = $1
RETURNING investment_id, ticker, exchange
`

type UpdateStockDetailsParams struct {
	InvestmentID uuid.UUID `json:"investment_id"`
	Ticker       string    `json:"ticker"`
	Exchange     string    `json:"exchange"`
}

func (q *Queries) UpdateStockDetails(ctx context.Context, arg UpdateStockDetailsParams) (StockDetail, error) {
	row := q.db.QueryRow(ctx, updateStockDetails, arg.InvestmentID, arg.Ticker, arg.Exchange)
	var i StockDetail
	err := row.Scan(&i.InvestmentID, &i.Ticker, &i.Exchange)
	return i, err
}
