// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const assignAssetTag = `-- name: AssignAssetTag :execrows

UPDATE assets
SET tag_id = $1, updated_by = $4, updated_at = now()
WHERE id = $2 AND household_id = $3 AND deleted_at IS NULL
`

type AssignAssetTagParams struct {
	TagID       *uuid.UUID `json:"tag_id"`
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

// ----- assignment (one per shared Position table) -------------------------
// tag_id ($1) is nullable: a NULL unassigns. The caller validates the Tag's
// household ownership before these run; the household_id filter here is the
// belt-and-suspenders Position-side guard (ADR-0028 tenancy).
func (q *Queries) AssignAssetTag(ctx context.Context, arg AssignAssetTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignAssetTag,
		arg.TagID,
		arg.ID,
		arg.HouseholdID,
		arg.UpdatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const assignInvestmentTag = `-- name: AssignInvestmentTag :execrows
UPDATE investments
SET tag_id = $1, updated_by = $4, updated_at = now()
WHERE id = $2 AND household_id = $3 AND deleted_at IS NULL
`

type AssignInvestmentTagParams struct {
	TagID       *uuid.UUID `json:"tag_id"`
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) AssignInvestmentTag(ctx context.Context, arg AssignInvestmentTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignInvestmentTag,
		arg.TagID,
		arg.ID,
		arg.HouseholdID,
		arg.UpdatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const assignLiabilityTag = `-- name: AssignLiabilityTag :execrows
UPDATE liabilities
SET tag_id = $1, updated_by = $4, updated_at = now()
WHERE id = $2 AND household_id = $3 AND deleted_at IS NULL
`

type AssignLiabilityTagParams struct {
	TagID       *uuid.UUID `json:"tag_id"`
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) AssignLiabilityTag(ctx context.Context, arg AssignLiabilityTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignLiabilityTag,
		arg.TagID,
		arg.ID,
		arg.HouseholdID,
		arg.UpdatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const assignReceivableTag = `-- name: AssignReceivableTag :execrows
UPDATE receivables
SET tag_id = $1, updated_by = $4, updated_at = now()
WHERE id = $2 AND household_id = $3 AND deleted_at IS NULL
`

type AssignReceivableTagParams struct {
	TagID       *uuid.UUID `json:"tag_id"`
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) AssignReceivableTag(ctx context.Context, arg AssignReceivableTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignReceivableTag,
		arg.TagID,
		arg.ID,
		arg.HouseholdID,
		arg.UpdatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearAssetTag = `-- name: ClearAssetTag :exec

UPDATE assets SET tag_id = NULL WHERE tag_id = $1 AND household_id = $2
`

type ClearAssetTagParams struct {
	TagID       *uuid.UUID `json:"tag_id"`
	HouseholdID uuid.UUID  `json:"household_id"`
}

// ----- unassign-on-delete (clear references so the Position reads Untagged) -
// Soft-deleting a Tag clears it everywhere in the same transaction, so no
// Position is left pointing at a dead Tag (ADR-0028).
func (q *Queries) ClearAssetTag(ctx context.Context, arg ClearAssetTagParams) error {
	_, err := q.db.Exec(ctx, clearAssetTag, arg.TagID, arg.HouseholdID)
	return err
}

const clearInvestmentTag = `-- name: ClearInvestmentTag :exec
UPDATE investments SET tag_id = NULL WHERE tag_id = $1 AND household_id = $2
`

type ClearInvestmentTagParams struct {
	TagID       *uuid.UUID `json:"tag_id"`
	HouseholdID uuid.UUID  `json:"household_id"`
}

func (q *Queries) ClearInvestmentTag(ctx context.Context, arg ClearInvestmentTagParams) error {
	_, err := q.db.Exec(ctx, clearInvestmentTag, arg.TagID, arg.HouseholdID)
	return err
}

const clearLiabilityTag = `-- name: ClearLiabilityTag :exec
UPDATE liabilities SET tag_id = NULL WHERE tag_id = $1 AND household_id = $2
`

type ClearLiabilityTagParams struct {
	TagID       *uuid.UUID `json:"tag_id"`
	HouseholdID uuid.UUID  `json:"household_id"`
}

func (q *Queries) ClearLiabilityTag(ctx context.Context, arg ClearLiabilityTagParams) error {
	_, err := q.db.Exec(ctx, clearLiabilityTag, arg.TagID, arg.HouseholdID)
	return err
}

const clearReceivableTag = `-- name: ClearReceivableTag :exec
UPDATE receivables SET tag_id = NULL WHERE tag_id = $1 AND household_id = $2
`

type ClearReceivableTagParams struct {
	TagID       *uuid.UUID `json:"tag_id"`
	HouseholdID uuid.UUID  `json:"household_id"`
}

func (q *Queries) ClearReceivableTag(ctx context.Context, arg ClearReceivableTagParams) error {
	_, err := q.db.Exec(ctx, clearReceivableTag, arg.TagID, arg.HouseholdID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (
    household_id, name, color, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $4
)
RETURNING id, household_id, name, color, created_by, created_at, updated_by, updated_at, deleted_at
`

type CreateTagParams struct {
	HouseholdID uuid.UUID  `json:"household_id"`
	Name        string     `json:"name"`
	Color       string     `json:"color"`
	CreatedBy   *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.HouseholdID,
		arg.Name,
		arg.Color,
		arg.CreatedBy,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Color,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, household_id, name, color, created_by, created_at, updated_by, updated_at, deleted_at
FROM tags
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type GetTagByIDParams struct {
	ID          uuid.UUID `json:"id"`
	HouseholdID uuid.UUID `json:"household_id"`
}

func (q *Queries) GetTagByID(ctx context.Context, arg GetTagByIDParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, arg.ID, arg.HouseholdID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Color,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTagsByHousehold = `-- name: ListTagsByHousehold :many
SELECT id, household_id, name, color, created_by, created_at, updated_by, updated_at, deleted_at
FROM tags
WHERE household_id = $1 AND deleted_at IS NULL
ORDER BY lower(name)
`

func (q *Queries) ListTagsByHousehold(ctx context.Context, householdID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.HouseholdID,
			&i.Name,
			&i.Color,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTag = `-- name: SoftDeleteTag :execrows
UPDATE tags
SET deleted_at = now(),
    updated_by = $3,
    updated_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
`

type SoftDeleteTagParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteTag(ctx context.Context, arg SoftDeleteTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTag, arg.ID, arg.HouseholdID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tagBreakdownByHousehold = `-- name: TagBreakdownByHousehold :many

SELECT tag_id, grp, currency, total FROM (
    SELECT a.tag_id AS tag_id, 'asset'::text AS grp, ls.currency AS currency,
           COALESCE(SUM(ls.amount), 0)::numeric AS total
    FROM assets a
    JOIN LATERAL (
        SELECT amount, currency FROM asset_snapshots
        WHERE asset_id = a.id AND deleted_at IS NULL
          AND year_month <= date_trunc('month', CURRENT_DATE)::date
        ORDER BY year_month DESC LIMIT 1
    ) ls ON true
    WHERE a.household_id = $1 AND a.deleted_at IS NULL
      AND (a.terminated_at IS NULL OR a.terminated_at >= date_trunc('month', CURRENT_DATE)::date)
    GROUP BY a.tag_id, ls.currency

    UNION ALL

    SELECT l.tag_id, 'liability'::text, ls.currency,
           COALESCE(SUM(ls.amount), 0)::numeric
    FROM liabilities l
    JOIN LATERAL (
        SELECT amount, currency FROM liability_snapshots
        WHERE liability_id = l.id AND deleted_at IS NULL
          AND year_month <= date_trunc('month', CURRENT_DATE)::date
        ORDER BY year_month DESC LIMIT 1
    ) ls ON true
    WHERE l.household_id = $1 AND l.deleted_at IS NULL
      AND (l.terminated_at IS NULL OR l.terminated_at >= date_trunc('month', CURRENT_DATE)::date)
    GROUP BY l.tag_id, ls.currency

    UNION ALL

    SELECT r.tag_id, 'receivable'::text, ls.currency,
           COALESCE(SUM(ls.amount), 0)::numeric
    FROM receivables r
    JOIN LATERAL (
        SELECT amount, currency FROM receivable_snapshots
        WHERE receivable_id = r.id AND deleted_at IS NULL
          AND year_month <= date_trunc('month', CURRENT_DATE)::date
        ORDER BY year_month DESC LIMIT 1
    ) ls ON true
    WHERE r.household_id = $1 AND r.deleted_at IS NULL
      AND (r.terminated_at IS NULL OR r.terminated_at >= date_trunc('month', CURRENT_DATE)::date)
    GROUP BY r.tag_id, ls.currency

    UNION ALL

    SELECT i.tag_id, 'investment'::text, ls.currency,
           COALESCE(SUM(ls.amount), 0)::numeric
    FROM investments i
    JOIN LATERAL (
        SELECT amount, currency FROM investment_snapshots
        WHERE investment_id = i.id AND deleted_at IS NULL
          AND year_month <= date_trunc('month', CURRENT_DATE)::date
        ORDER BY year_month DESC LIMIT 1
    ) ls ON true
    WHERE i.household_id = $1 AND i.deleted_at IS NULL
      AND (i.terminated_at IS NULL OR i.terminated_at >= date_trunc('month', CURRENT_DATE)::date)
    GROUP BY i.tag_id, ls.currency
) breakdown
ORDER BY grp, currency
`

type TagBreakdownByHouseholdRow struct {
	TagID    *uuid.UUID      `json:"tag_id"`
	Grp      string          `json:"grp"`
	Currency string          `json:"currency"`
	Total    decimal.Decimal `json:"total"`
}

// ----- breakdown report ----------------------------------------------------
// Per (tag_id, group, currency): the summed most-recent-snapshot value of
// every contributing Position. tag_id NULL = the Untagged bucket. A Position
// contributes its latest snapshot with year_month <= the current month, and
// only while active or terminated in/after the current month (the net-worth
// carry-forward + termination rule, CONTEXT "Net Worth"). Liabilities ride
// back under grp='liability' so the report layer can show them as their own
// (negative) slice rather than netting them into a tag's assets.
func (q *Queries) TagBreakdownByHousehold(ctx context.Context, householdID uuid.UUID) ([]TagBreakdownByHouseholdRow, error) {
	rows, err := q.db.Query(ctx, tagBreakdownByHousehold, householdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TagBreakdownByHouseholdRow
	for rows.Next() {
		var i TagBreakdownByHouseholdRow
		if err := rows.Scan(
			&i.TagID,
			&i.Grp,
			&i.Currency,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name       = $3,
    color      = $4,
    updated_by = $5,
    updated_at = now()
WHERE id = $1 AND household_id = $2 AND deleted_at IS NULL
RETURNING id, household_id, name, color, created_by, created_at, updated_by, updated_at, deleted_at
`

type UpdateTagParams struct {
	ID          uuid.UUID  `json:"id"`
	HouseholdID uuid.UUID  `json:"household_id"`
	Name        string     `json:"name"`
	Color       string     `json:"color"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag,
		arg.ID,
		arg.HouseholdID,
		arg.Name,
		arg.Color,
		arg.UpdatedBy,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Name,
		&i.Color,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
