// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: time_deposits.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createTimeDepositDetails = `-- name: CreateTimeDepositDetails :one
INSERT INTO time_deposit_details (
    investment_id, bank_name, principal, interest_rate,
    term_months, placement_date, maturity_date, rollover_policy
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING investment_id, bank_name, principal, interest_rate, term_months, placement_date, maturity_date, rollover_policy
`

type CreateTimeDepositDetailsParams struct {
	InvestmentID   uuid.UUID       `json:"investment_id"`
	BankName       string          `json:"bank_name"`
	Principal      decimal.Decimal `json:"principal"`
	InterestRate   decimal.Decimal `json:"interest_rate"`
	TermMonths     int32           `json:"term_months"`
	PlacementDate  time.Time       `json:"placement_date"`
	MaturityDate   time.Time       `json:"maturity_date"`
	RolloverPolicy string          `json:"rollover_policy"`
}

func (q *Queries) CreateTimeDepositDetails(ctx context.Context, arg CreateTimeDepositDetailsParams) (TimeDepositDetail, error) {
	row := q.db.QueryRow(ctx, createTimeDepositDetails,
		arg.InvestmentID,
		arg.BankName,
		arg.Principal,
		arg.InterestRate,
		arg.TermMonths,
		arg.PlacementDate,
		arg.MaturityDate,
		arg.RolloverPolicy,
	)
	var i TimeDepositDetail
	err := row.Scan(
		&i.InvestmentID,
		&i.BankName,
		&i.Principal,
		&i.InterestRate,
		&i.TermMonths,
		&i.PlacementDate,
		&i.MaturityDate,
		&i.RolloverPolicy,
	)
	return i, err
}

const getTimeDepositDetailsByInvestmentID = `-- name: GetTimeDepositDetailsByInvestmentID :one
SELECT investment_id, bank_name, principal, interest_rate, term_months, placement_date, maturity_date, rollover_policy
FROM time_deposit_details
WHERE investment_id = $1
`

func (q *Queries) GetTimeDepositDetailsByInvestmentID(ctx context.Context, investmentID uuid.UUID) (TimeDepositDetail, error) {
	row := q.db.QueryRow(ctx, getTimeDepositDetailsByInvestmentID, investmentID)
	var i TimeDepositDetail
	err := row.Scan(
		&i.InvestmentID,
		&i.BankName,
		&i.Principal,
		&i.InterestRate,
		&i.TermMonths,
		&i.PlacementDate,
		&i.MaturityDate,
		&i.RolloverPolicy,
	)
	return i, err
}

const listTimeDepositDetailsByInvestmentIDs = `-- name: ListTimeDepositDetailsByInvestmentIDs :many
SELECT investment_id, bank_name, principal, interest_rate, term_months, placement_date, maturity_date, rollover_policy
FROM time_deposit_details
WHERE investment_id = ANY($1::uuid[])
`

func (q *Queries) ListTimeDepositDetailsByInvestmentIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]TimeDepositDetail, error) {
	rows, err := q.db.Query(ctx, listTimeDepositDetailsByInvestmentIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeDepositDetail
	for rows.Next() {
		var i TimeDepositDetail
		if err := rows.Scan(
			&i.InvestmentID,
			&i.BankName,
			&i.Principal,
			&i.InterestRate,
			&i.TermMonths,
			&i.PlacementDate,
			&i.MaturityDate,
			&i.RolloverPolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimeDepositDetails = `-- name: UpdateTimeDepositDetails :one
UPDATE time_deposit_details
SET bank_name        = $2,
    principal        = $3,
    interest_rate    = $4,
    term_months      = $5,
    placement_date   = $6,
    maturity_date    = $7,
    rollover_policy  = $8
WHERE investment_id = $1
RETURNING investment_id, bank_name, principal, interest_rate, term_months, placement_date, maturity_date, rollover_policy
`

type UpdateTimeDepositDetailsParams struct {
	InvestmentID   uuid.UUID       `json:"investment_id"`
	BankName       string          `json:"bank_name"`
	Principal      decimal.Decimal `json:"principal"`
	InterestRate   decimal.Decimal `json:"interest_rate"`
	TermMonths     int32           `json:"term_months"`
	PlacementDate  time.Time       `json:"placement_date"`
	MaturityDate   time.Time       `json:"maturity_date"`
	RolloverPolicy string          `json:"rollover_policy"`
}

func (q *Queries) UpdateTimeDepositDetails(ctx context.Context, arg UpdateTimeDepositDetailsParams) (TimeDepositDetail, error) {
	row := q.db.QueryRow(ctx, updateTimeDepositDetails,
		arg.InvestmentID,
		arg.BankName,
		arg.Principal,
		arg.InterestRate,
		arg.TermMonths,
		arg.PlacementDate,
		arg.MaturityDate,
		arg.RolloverPolicy,
	)
	var i TimeDepositDetail
	err := row.Scan(
		&i.InvestmentID,
		&i.BankName,
		&i.Principal,
		&i.InterestRate,
		&i.TermMonths,
		&i.PlacementDate,
		&i.MaturityDate,
		&i.RolloverPolicy,
	)
	return i, err
}
