// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    household_id, display_name, email, google_sub, locale, time_zone, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $7
)
RETURNING id, household_id, display_name, email, google_sub, locale, time_zone, created_by, created_at, updated_by, updated_at, deleted_at
`

type CreateUserParams struct {
	HouseholdID uuid.UUID  `json:"household_id"`
	DisplayName string     `json:"display_name"`
	Email       string     `json:"email"`
	GoogleSub   string     `json:"google_sub"`
	Locale      string     `json:"locale"`
	TimeZone    string     `json:"time_zone"`
	CreatedBy   *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.HouseholdID,
		arg.DisplayName,
		arg.Email,
		arg.GoogleSub,
		arg.Locale,
		arg.TimeZone,
		arg.CreatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Email,
		&i.GoogleSub,
		&i.Locale,
		&i.TimeZone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, household_id, display_name, email, google_sub, locale, time_zone, created_by, created_at, updated_by, updated_at, deleted_at
FROM users
WHERE google_sub = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Email,
		&i.GoogleSub,
		&i.Locale,
		&i.TimeZone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, household_id, display_name, email, google_sub, locale, time_zone, created_by, created_at, updated_by, updated_at, deleted_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.DisplayName,
		&i.Email,
		&i.GoogleSub,
		&i.Locale,
		&i.TimeZone,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
