// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicles.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createVehicleDetails = `-- name: CreateVehicleDetails :one
INSERT INTO vehicle_details (
    asset_id, vehicle_type, make, model, year,
    plate_number, annual_depreciation_rate
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING asset_id, vehicle_type, make, model, year, plate_number, annual_depreciation_rate
`

type CreateVehicleDetailsParams struct {
	AssetID                uuid.UUID        `json:"asset_id"`
	VehicleType            string           `json:"vehicle_type"`
	Make                   *string          `json:"make"`
	Model                  *string          `json:"model"`
	Year                   *int32           `json:"year"`
	PlateNumber            *string          `json:"plate_number"`
	AnnualDepreciationRate *decimal.Decimal `json:"annual_depreciation_rate"`
}

func (q *Queries) CreateVehicleDetails(ctx context.Context, arg CreateVehicleDetailsParams) (VehicleDetail, error) {
	row := q.db.QueryRow(ctx, createVehicleDetails,
		arg.AssetID,
		arg.VehicleType,
		arg.Make,
		arg.Model,
		arg.Year,
		arg.PlateNumber,
		arg.AnnualDepreciationRate,
	)
	var i VehicleDetail
	err := row.Scan(
		&i.AssetID,
		&i.VehicleType,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.PlateNumber,
		&i.AnnualDepreciationRate,
	)
	return i, err
}

const getVehicleDetailsByAssetID = `-- name: GetVehicleDetailsByAssetID :one
SELECT asset_id, vehicle_type, make, model, year, plate_number, annual_depreciation_rate
FROM vehicle_details
WHERE asset_id = $1
`

func (q *Queries) GetVehicleDetailsByAssetID(ctx context.Context, assetID uuid.UUID) (VehicleDetail, error) {
	row := q.db.QueryRow(ctx, getVehicleDetailsByAssetID, assetID)
	var i VehicleDetail
	err := row.Scan(
		&i.AssetID,
		&i.VehicleType,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.PlateNumber,
		&i.AnnualDepreciationRate,
	)
	return i, err
}

const listVehicleDetailsByAssetIDs = `-- name: ListVehicleDetailsByAssetIDs :many
SELECT asset_id, vehicle_type, make, model, year, plate_number, annual_depreciation_rate
FROM vehicle_details
WHERE asset_id = ANY($1::uuid[])
`

func (q *Queries) ListVehicleDetailsByAssetIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]VehicleDetail, error) {
	rows, err := q.db.Query(ctx, listVehicleDetailsByAssetIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleDetail
	for rows.Next() {
		var i VehicleDetail
		if err := rows.Scan(
			&i.AssetID,
			&i.VehicleType,
			&i.Make,
			&i.Model,
			&i.Year,
			&i.PlateNumber,
			&i.AnnualDepreciationRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicleDetails = `-- name: UpdateVehicleDetails :one
UPDATE vehicle_details
SET vehicle_type             = $2,
    make                     = $3,
    model                    = $4,
    year                     = $5,
    plate_number             = $6,
    annual_depreciation_rate = $7
WHERE asset_id = $1
RETURNING asset_id, vehicle_type, make, model, year, plate_number, annual_depreciation_rate
`

type UpdateVehicleDetailsParams struct {
	AssetID                uuid.UUID        `json:"asset_id"`
	VehicleType            string           `json:"vehicle_type"`
	Make                   *string          `json:"make"`
	Model                  *string          `json:"model"`
	Year                   *int32           `json:"year"`
	PlateNumber            *string          `json:"plate_number"`
	AnnualDepreciationRate *decimal.Decimal `json:"annual_depreciation_rate"`
}

func (q *Queries) UpdateVehicleDetails(ctx context.Context, arg UpdateVehicleDetailsParams) (VehicleDetail, error) {
	row := q.db.QueryRow(ctx, updateVehicleDetails,
		arg.AssetID,
		arg.VehicleType,
		arg.Make,
		arg.Model,
		arg.Year,
		arg.PlateNumber,
		arg.AnnualDepreciationRate,
	)
	var i VehicleDetail
	err := row.Scan(
		&i.AssetID,
		&i.VehicleType,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.PlateNumber,
		&i.AnnualDepreciationRate,
	)
	return i, err
}
